server:
  port:
    8081

eureka:
  instance: 
    hostname: ec2-18-218-251-25.us-east-2.compute.amazonaws.com
    port: 9000
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
    server:
      wait-time-in-ms-when-sync-empty: 3000 
